[platformio]
default_envs = esp32-sensor-logger

[env:esp32-sensor-logger]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 921600
lib_deps =
    adafruit/Adafruit Unified Sensor
    adafruit/Adafruit ADXL345
